### ISSUE TITLE
Creating a file with a size of 300 MB while doing "Build"

### ISSUE THREAD

**Issue by MhmudAlpurd** [windmaple/tflite-asr#1]
Hi, thank you for this guide. I have a question about that, The output file (apk) of this code is very large due to creating a build folder (300MB) automatically, and this makes the file (apk) useless. is there any solution to solve this?

Thank you.

**Comment by windmaple** [comment]
This is a generic Android question. You should check out [Android guide](https://developer.android.com/topic/performance/reduce-apk-size)

On TFLite side, you should look into re-convert the CONFORMER model using the latest converter. There were some TensorFlow ops that bring in Flex dependency; those ops may have been made TFLite built-in ops, in which case you can reduce the a few MBs further.

Hope this helps.

**Comment by MhmudAlpurd** [comment]
thank you @windmaple , Is the size of your Android apk so big when you run Android code? Do you have a similar experience?

**Comment by windmaple** [comment]
I didn't check. This is supposed to be a reference app, not a production app. It's a long way to go from reference to production.

**Comment by MhmudAlpurd** [comment]
@windmaple, thanks a lot for your quick responses.
